In [20]:
from IPython.display import display, Math, Latex

**Introduction**

In [1]:
import numpy as np


Create a numpy array from a python array

In [51]:
python_array = [range(20), range(20), range(20)] 

Generate two random numpy arrays A and B of size (3, 5), calculate A + B, A - B, A * B, A / B  

In [22]:
A = np.random.randint(low=0, high=10, size= (3, 5) )
B = np.random.randint(low=0, high=10, size= (3, 5) )

In [23]:
A

array([[1, 9, 5, 8, 9],
       [5, 9, 3, 6, 2],
       [9, 3, 6, 7, 7]])

In [24]:
B

array([[8, 5, 1, 5, 5],
       [5, 9, 6, 3, 3],
       [1, 8, 3, 5, 0]])

In [25]:
np.dot(A,np.transpose(B))

array([[143, 167, 128],
       [128, 148, 116],
       [163, 150,  86]])

Sum up the elements of A by two methods:
- Run a 'for' loop
- Using np.sum 


Find 3 different ways to transform A into a 1 dimensional array of size 15

Find a way to concatenate A and B into one array C of size (3,10) and an array D of size (6,5)

Now find a way to split C into A and B, similary D into A and B

**Indexing**

Print second row and second column of A

Swapping the second row of A with the third row of B. Swapping the third column of A with the first column of B.

Imagine that the values in A is pixel intensity of a B&W image (on some scale), could you flip A horizontally and vertically

Advanced indexing: 
Try the following code, explaining the difference:

In [ ]:
T = [[0,1,0], [1,2,1]]

print A[T]

In [ ]:
T = np.array(T)

print A[T]

Boolean indexing: Select all elements in A that are larger than 5

Select all elements in A that are larger than 5 and smaller than 8

** Some other numpy methods **

Randomly generate two probability distributions P with three outcomes 0, 1, 2 and Q with three outcomes 2, 3, 4. What is the probability distribution of P + Q?

Find all elements that has the highest value in A